### ISSUE TITLE
从8月14日开始断签了

### ISSUE THREAD

**Issue by vulkanparagon** [Xzonn/TjuptAutoAttendance#1]
看了一下Actions是在正常运行的，之前一直都没有问题，刚才手动运行了一遍发现显示正常工作，但是在tjupt网页端显示没有签到。

**Comment by Xzonn** [comment]
看了下其他几个 Fork，都能正常运行，我自己本地运行也没问题，推测是个人设置导致验证码图片没有被识别。
需要确认一下，你有没有设置过自定义 CSS、修改默认主题？如果方便的话，能否提供“控制面板”→“网站设定”的截图以及签到页面的截图（涉及个人信息的部分可裁减掉或打马赛克）？谢谢！

**Comment by vulkanparagon** [comment]
自定义CSS应该是没有设置过的。从7月31日到8月13日都是可以正常使用。
![17-8-2022_123244_tjupt org](https://user-images.githubusercontent.com/46082852/185035498-8c7f9d8b-d493-4525-82f8-9dc79e194832.jpeg)
![17-8-2022_123143_tjupt org](https://user-images.githubusercontent.com/46082852/185035503-208ac420-fa87-4760-bf2f-b40177862159.jpeg)

**Comment by Xzonn** [comment]
发现问题了，应该是 8 月 14 日当天签到未成功，之后签到页面会先询问是否补签，而代码里面没考虑这种情况。
8 月 14 日未成功是因为“验证码识别”实际上是调用的豆瓣接口，而豆瓣大概是设置了反爬虫规则，多次调用的话直接就返回空值，找不到正确选项，所以签到失败了。我试一下增加请求头的参数，看看是否有效。
如果方便的话，可否提供一下补签页面的链接（对超链接右键→复制链接地址）以及补签页面的截图？

**Comment by vulkanparagon** [comment]
选择补签的链接：https://tjupt.org/attendance.php?action=confirm
然后点击补签跳转的应该就是正常的签到页面：https://tjupt.org/attendance.php?action=confirm
![17-8-2022_14643_tjupt org](https://user-images.githubusercontent.com/46082852/185046562-763b5a8a-1a70-495e-a6c6-5333ee280814.jpeg)
由于我现在只能补签一天，所以选对了也没法补签
![17-8-2022_1499_tjupt org](https://user-images.githubusercontent.com/46082852/185046937-2d329718-3b42-43ec-976e-37e0f2edfa5d.jpeg)
大概就是这个流程，我重新开始签到吧。

感谢作者辛苦付出！

**Comment by Xzonn** [comment]
感谢反馈，我增加了尝试次数，并且添加了签到失败的错误提示。
因为这个项目本来也是我自己用的，考虑的情况可能不是很全面，如果还有问题请继续反馈，谢谢！

**Comment by vulkanparagon** [comment]
哈哈好的，写的已经非常好了！
再次感谢！

**Comment by Xzonn** [comment]
最近应该没出问题了，先把这个 Issue 关了，有问题的话请继续反馈。
